/** 种子风格（awesome-design-md）的分组与一句话描述，来源：上游 README.md */
export const SEED_CATEGORIES: Record<string, string> = {
  // AI 与机器学习
  claude: 'AI 与机器学习', cohere: 'AI 与机器学习', elevenlabs: 'AI 与机器学习', minimax: 'AI 与机器学习',
  'mistral.ai': 'AI 与机器学习', ollama: 'AI 与机器学习', 'opencode.ai': 'AI 与机器学习', replicate: 'AI 与机器学习',
  runwayml: 'AI 与机器学习', 'together.ai': 'AI 与机器学习', voltagent: 'AI 与机器学习', 'x.ai': 'AI 与机器学习',
  // 开发工具与平台
  cursor: '开发工具与平台', expo: '开发工具与平台', 'linear.app': '开发工具与平台', lovable: '开发工具与平台',
  mintlify: '开发工具与平台', posthog: '开发工具与平台', raycast: '开发工具与平台', resend: '开发工具与平台',
  sentry: '开发工具与平台', supabase: '开发工具与平台', superhuman: '开发工具与平台', vercel: '开发工具与平台',
  warp: '开发工具与平台', zapier: '开发工具与平台',
  // 基础设施与云
  clickhouse: '基础设施与云', composio: '基础设施与云', hashicorp: '基础设施与云', mongodb: '基础设施与云',
  sanity: '基础设施与云', stripe: '基础设施与云',
  // 设计与生产力
  airtable: '设计与生产力', cal: '设计与生产力', clay: '设计与生产力', figma: '设计与生产力',
  framer: '设计与生产力', intercom: '设计与生产力', miro: '设计与生产力', notion: '设计与生产力',
  pinterest: '设计与生产力', webflow: '设计与生产力',
  // 金融与加密
  coinbase: '金融与加密', kraken: '金融与加密', revolut: '金融与加密', wise: '金融与加密',
  // 企业与消费
  airbnb: '企业与消费', apple: '企业与消费', bmw: '企业与消费', ibm: '企业与消费',
  nvidia: '企业与消费', spacex: '企业与消费', spotify: '企业与消费', uber: '企业与消费',
};

export const SEED_DESCRIPTIONS: Record<string, string> = {
  airbnb: '珊瑚暖色调、照片驱动的旅行民宿平台',
  airtable: '彩色友好的电子表格-数据库混合体',
  apple: '高级留白、SF Pro、影院级产品影像',
  bmw: '深色高端质感、德系精密工程美学',
  cal: '干净中性的开源排期工具',
  claude: '陶土暖色点缀、编辑式排版的 AI 助手',
  clay: '有机形状、柔和渐变的创意机构',
  clickhouse: '黄色点缀、技术文档风的极速分析数据库',
  cohere: '鲜艳渐变、数据密集仪表盘感的企业 AI 平台',
  coinbase: '信任导向、干净蓝色机构感的交易所',
  composio: '现代深色 + 彩色集成图标的工具平台',
  cursor: 'AI 优先代码编辑器、深色界面渐变点缀',
  elevenlabs: '电影感深色 UI、音频波形美学',
  expo: '深色主题、紧凑字距的 React Native 平台',
  figma: '多彩而专业的协作设计工具',
  framer: '黑蓝大胆、动效优先的建站工具',
  hashicorp: '企业级黑白的基础设施自动化',
  ibm: 'Carbon 设计系统、结构化蓝色企业风',
  intercom: '友好蓝色、对话式 UI 的客户消息平台',
  kraken: '紫色点缀深色 UI、数据密集的交易平台',
  'linear.app': '近黑画布、极致精密、靛紫点缀',
  lovable: '顽皮渐变、友好的开发者美学',
  minimax: '大胆深色界面 + 霓虹点缀',
  mintlify: '干净绿色点缀、阅读优化的文档平台',
  'mistral.ai': '法式极简、紫色调的开源 LLM 提供商',
  mongodb: '绿叶品牌、开发者文档优先',
  miro: '亮黄点缀、无限画布感的视觉协作',
  notion: '暖色极简、衬线标题、柔和表面',
  nvidia: '绿黑能量感、算力美学',
  ollama: '终端优先、单色简约的本地 LLM',
  'opencode.ai': '开发者中心的深色主题 AI 编码平台',
  pinterest: '红色点缀、瀑布流、图片优先',
  posthog: '顽皮刺猬品牌、开发者友好深色 UI',
  raycast: '深色铬感、鲜艳渐变的生产力启动器',
  replicate: '干净白画布、代码优先的模型 API',
  resend: '极简深色、等宽点缀的邮件 API',
  revolut: '时尚深色界面、渐变卡片的数字银行',
  runwayml: '电影感深色、媒体丰富的 AI 视频生成',
  sanity: '红色点缀、内容优先编辑排版的 CMS',
  sentry: '深色仪表盘、数据密集、粉紫点缀',
  spacex: '黑白强烈对比、全幅影像、未来感',
  spotify: '深色上的活力绿、粗体字、专辑艺术驱动',
  stripe: '标志性紫色渐变、300 字重的优雅',
  supabase: '深祖母绿主题、代码优先的开源后端',
  superhuman: '高级深色 UI、键盘优先、紫色光晕',
  'together.ai': '蓝图式技术感的开源 AI 基础设施',
  uber: '黑白大胆、紧凑字体、都市能量',
  vercel: '黑白精密、Geist 字体的部署平台',
  voltagent: '纯黑画布、翡翠绿点缀、终端原生',
  warp: '深色 IDE 感、块状命令 UI 的现代终端',
  webflow: '蓝色点缀、精致的营销站美学建站工具',
  wise: '亮绿色点缀、友好清晰的国际转账',
  'x.ai': '纯粹单色、未来极简',
  zapier: '暖橙色、友好插画驱动的自动化平台',
};

export const SEED_CATEGORY_ORDER = [
  'AI 与机器学习',
  '开发工具与平台',
  '基础设施与云',
  '设计与生产力',
  '金融与加密',
  '企业与消费',
];
